project_id = "dazdotcdpudxpycodbbe"

[functions.send-invoice-email]
verify_jwt = false

[functions.send-payment-reminders]
verify_jwt = false

[functions.cleanup-old-documents]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false
